services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/ankitprasad2005/defdrive:latest
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - WORKERS=${WORKERS}
      # - DB_HOST=db
      # - DB_PORT=5432
      # - DB_USER=${DB_USER}
      # - DB_PASSWD=${DB_PASSWD}
      # - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - TZ=${TZ}
      - PORT=8080
      - DATA_PATH=/app/data
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./data:/app/data
    depends_on:
      db: 
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:latest
    user: 999:999
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      interval: 10s
      retries: 10
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 2s
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "${MINIO_PORT}:9000"  # API port
      - "${MINIO_CONSOLE_PORT}:9001"  # Console port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      # - minio_data:/data
      - ${MINIO_DATA}:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # admin_db:
  #   image: nocodb/nocodb:latest
  #   environment:
  #     NC_DB: pg://db:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${POSTGRES_DB}
  #   volumes:
  #     - nc_data:/usr/app/data
  #   ports:
  #     - ${PORT_ADMIN}:8080
  #   depends_on:
  #     - db

