services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - WORKERS=${WORKERS}
      # - DB_HOST=db
      # - DB_PORT=5432
      # - DB_USER=${DB_USER}
      # - DB_PASSWD=${DB_PASSWD}
      # - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - TZ=${TZ}
      - PORT=8080
      - DATA_PATH=/app/data
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - ./data:/app/data
    depends_on:
      db: 
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:14
    # user: ${UID}:${GID}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      interval: 10s
      retries: 10
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 2s
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432

  # admin_db:
  #   image: nocodb/nocodb:latest
  #   environment:
  #     NC_DB: pg://db:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${POSTGRES_DB}
  #   volumes:
  #     - nc_data:/usr/app/data
  #   ports:
  #     - ${PORT_ADMIN}:8080
  #   depends_on:
  #     - db

volumes:
  db_data: {}
